collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 1
color:
  saturation: 1
  brandStrength: 0.9830705337226391
  lightness: 1
  brandColors:
    - '#BED482'
    - '#68938C'
    - '#3A5D79'
    - '#FFFFFF'
    - '#FFC071'
  rhythmicContrast: 0.5404721
layout_spectrum: 0.8608769
name: sotothemuse
